/* Iris: altre 50 animazioni nuove (secondo lotto del 04/10): 16 varianti degli stati (2 per stato) e 34 easter egg.
   Stesso formato di eyes-nuove.js, che va caricato prima. */
(function () {
  const Iris = window.Iris;
  const { mk, clamp, CY, prand, f2, STAR, HEART } = Iris._fx;
  const tr = (n, x, y, sc = 1, rot = 0) => n.setAttribute("transform", `translate(${f2(x)} ${f2(y)}) rotate(${f2(rot)}) scale(${f2(Math.max(0, sc))})`);
  const op = (n, v) => n.setAttribute("opacity", f2(clamp(v, 0, 1)));
  const ease = (k) => k * k * (3 - 2 * k);
  const seg = (k, a, b) => clamp((k - a) / (b - a), 0, 1);
  const look = (T, x, y, a = 1) => { for (const [e, cx] of [[T.L, 46], [T.R, 74]]) { e.dx = clamp((x - cx) * 0.2, -5, 5) * a; e.dy = clamp((y - 61) * 0.35, -4, 4) * a; } };
  const both = (T, f) => { f(T.L); f(T.R); };
  const txt = (p, s, at) => { const n = mk(p, "text", Object.assign({ "font-family": "system-ui,sans-serif", "font-weight": 800, "text-anchor": "middle", "dominant-baseline": "middle" }, at)); n.textContent = s; return n; };
  const hideEyes = (T) => { T.L.op = T.R.op = 0; };

  /* =============== VARIANTI (2 per stato) =============== */
  const V = {
    listening: [
      { name: "Puntini che ballano", desc: "Tre puntini sotto gli occhi saltano più o meno in alto secondo quanto forte parli.",
        init(o, g) { g.d = [0, 1, 2].map((i) => mk(o.r.vfx, "circle", { cx: 54 + i * 6, r: 1.6, fill: "currentColor" })); },
        t(o, T) { T.waves = 0; T.body.rot = 0; both(T, (e) => { e.h = 19; e.dy = -2.5; }); },
        draw(o, t, ts, s, lvl, g) { g.d.forEach((d, i) => d.setAttribute("cy", f2(76 - Math.abs(Math.sin(s * 9 + i * 1.1)) * (0.5 + lvl * 4)))); } },
      { name: "Battito", desc: "Gli occhi si gonfiano e si sgonfiano insieme alla tua voce, come un cuore che batte.",
        t(o, T, ts, s, lvl) { T.waves = 0; T.body.rot = 0; both(T, (e) => { e.sc = 0.95 + lvl * 0.2; e.lb = 0.12; }); } },
    ],
    thinking: [
      { name: "Orbita", desc: "Un puntino gira intorno agli occhi come un elettrone, e lo sguardo lo segue.",
        init(o, g) { g.o = mk(o.r.vfx, "ellipse", { cx: 60, cy: 61, rx: 26, ry: 10, fill: "none", stroke: "currentColor", "stroke-width": 0.5, opacity: 0.35 }); g.d = mk(o.r.vfx, "circle", { r: 1.6, fill: "currentColor" }); },
        t(o, T, ts, s) { T.dots = 0; const an = s * 2.2; look(T, 60 + Math.cos(an) * 26, 61 + Math.sin(an) * 10); },
        draw(o, t, ts, s, lvl, g) { const an = s * 2.2; g.d.setAttribute("cx", f2(60 + Math.cos(an) * 26)); g.d.setAttribute("cy", f2(61 + Math.sin(an) * 10)); } },
    ],
    tool: [
      { name: "Lente d'ingrandimento", desc: "Una lente passa davanti agli occhi: quello sotto la lente diventa grande.",
        init(o, g) { const l = mk(o.r.vfx, "g", {}); mk(l, "circle", { r: 8, fill: "none", stroke: "#e2e8f0", "stroke-width": 1.4 }); mk(l, "line", { x1: 5.7, y1: 5.7, x2: 10, y2: 10, stroke: "#e2e8f0", "stroke-width": 2, "stroke-linecap": "round" }); g.l = l; },
        lx(s) { return 60 + Math.sin(s * 1.4) * 18; },
        t(o, T, ts, s) { const x = this.lx(s); for (const [e, cx] of [[T.L, 46], [T.R, 74]]) { const near = Math.max(0, 1 - Math.abs(x - cx) / 14); e.sc = 1 + near * 0.35; e.lt = 0.15; } },
        draw(o, t, ts, s, lvl, g) { tr(g.l, this.lx(s), 61); } },
      { name: "Martello", desc: "Un martelletto picchia accanto a lui con le scintille: a ogni colpo sbatte le palpebre.",
        init(o, g) { const h = mk(o.r.vfx, "g", {}); mk(h, "rect", { x: -0.8, y: -9, width: 1.6, height: 9, rx: 0.6, fill: "#a16207" }); mk(h, "rect", { x: -3.5, y: -11, width: 7, height: 3.2, rx: 0.8, fill: "#cbd5e1" }); g.h = h; g.sp = [0, 1, 2].map(() => mk(o.r.vfx, "line", { stroke: "#fde047", "stroke-width": 0.8, "stroke-linecap": "round" })); },
        hit(s) { const q = (s % 0.7) / 0.7; return q < 0.15 ? 1 - q / 0.15 : 0; },
        t(o, T, ts, s) { const h = this.hit(s); both(T, (e) => { e.dx = 4; e.lt = 0.2 + h * 0.6; e.h = 17; }); },
        draw(o, t, ts, s, lvl, g) { const q = (s % 0.7) / 0.7, an = q < 0.15 ? 0 : -50 * Math.sin(((q - 0.15) / 0.85) * Math.PI); tr(g.h, 106, 75, 1, an - 20); const h = this.hit(s); g.sp.forEach((l, i) => { const a = (-40 - i * 50) * Math.PI / 180; l.setAttribute("x1", f2(100 + Math.cos(a) * 2)); l.setAttribute("y1", f2(73 + Math.sin(a) * 2)); l.setAttribute("x2", f2(100 + Math.cos(a) * 5)); l.setAttribute("y2", f2(73 + Math.sin(a) * 5)); op(l, h); }); } },
    ],
    replying: [
      { name: "Barre del parlato", desc: "Sotto gli occhi cinque barrette salgono e scendono a ritmo delle parole.",
        init(o, g) { g.b = [0, 1, 2, 3, 4].map((i) => mk(o.r.vfx, "rect", { x: 50 + i * 4.4, width: 2.4, rx: 1.2, fill: "currentColor" })); },
        t(o, T) { both(T, (e) => { e.h = 18; e.dy = -3; e.lb = 0.15; }); },
        draw(o, t, ts, s, lvl, g) { g.b.forEach((b, i) => { const h = 1.5 + Math.abs(Math.sin(s * (7 + i * 1.3) + i)) * Math.abs(Math.sin(s * 2.3 + i)) * 6; b.setAttribute("y", f2(78 - h)); b.setAttribute("height", f2(h)); }); } },
      { name: "Lettere che volano", desc: "Mentre parla, piccole lettere escono e volano via verso destra.",
        init(o, g) { g.l = Array.from({ length: 5 }, (_, i) => txt(o.r.vfx, "abcdefghilmnopqrstuvz"[Math.floor(prand(i) * 21)], { "font-size": 5, fill: "currentColor", opacity: 0 })); },
        t(o, T, ts, s) { const y = Math.abs(Math.sin(s * 7.5)); both(T, (e) => { e.dy = -y; e.lb = 0.2; e.dx = -2; }); },
        draw(o, t, ts, s, lvl, g) { g.l.forEach((l, i) => { const q = (s * 0.8 + i / 5) % 1; tr(l, 84 + q * 46, 61 + Math.sin(q * 7 + i) * 6, 0.8 + q * 0.5, Math.sin(q * 5 + i) * 20); op(l, Math.sin(q * Math.PI)); }); } },
    ],
    done: [
      { name: "Pollice in su", desc: "Spunta un pollice alzato accanto agli occhi felici: tutto a posto.",
        init(o, g) { const p = mk(o.r.vfx, "g", { fill: "#fde68a" }); mk(p, "rect", { x: -4, y: -1, width: 7, height: 7, rx: 1.6 }); mk(p, "rect", { x: -3, y: -7, width: 3, height: 7, rx: 1.5 }); mk(p, "path", { d: "M-4 1.5 h7 M-4 3.8 h7", stroke: "#a16207", "stroke-width": 0.4 }); g.p = p; },
        t(o, T) { T.L.lb = T.R.lb = 0.55; T.L.dx = T.R.dx = -1.5; },
        draw(o, t, ts, s, lvl, g) { const k = clamp(ts / 400, 0, 1); tr(g.p, 98, 63 + (1 - ease(k)) * 10, 0.6 + ease(k) * 0.5, -12 + Math.sin(ts / 150) * 4 * (1 - clamp(ts / 1500, 0, 1))); op(g.p, k); } },
      { name: "Coppa", desc: "Una coppetta d'oro sale con un luccichio: missione compiuta.",
        init(o, g) { const c = mk(o.r.vfx, "g", {}); mk(c, "path", { d: "M-4 -5 h8 v2 a4 4 0 0 1 -8 0z M-1 1 h2 v3 h-2z M-3 4 h6 v1.5 h-6z", fill: "#fbbf24" }); mk(c, "path", { d: "M-4 -4 h-1.6 a1.6 1.6 0 0 0 1.6 3 M4 -4 h1.6 a1.6 1.6 0 0 1 -1.6 3", fill: "none", stroke: "#fbbf24", "stroke-width": 0.8 }); g.st = mk(c, "path", { d: STAR, fill: "#fff", transform: "translate(-2 -3) scale(0.5)" }); g.c = c; },
        t(o, T) { T.L.lb = T.R.lb = 0.55; },
        draw(o, t, ts, s, lvl, g) { const k = ease(clamp(ts / 500, 0, 1)); tr(g.c, 100, 70 - k * 8, 0.7 + k * 0.3); op(g.c, k); op(g.st, Math.abs(Math.sin(ts / 200))); } },
    ],
    approval: [
      { name: "Semaforo", desc: "Un semaforino accanto a lui lampeggia sul giallo: aspetta che gli dai il verde.",
        init(o, g) { const s = mk(o.r.vfx, "g", {}); mk(s, "rect", { x: -3, y: -8.5, width: 6, height: 17, rx: 2, fill: "#1e293b", stroke: "#475569", "stroke-width": 0.5 }); g.c = [["#7f1d1d", -5], ["#fde047", 0], ["#14532d", 5]].map(([c, y]) => mk(s, "circle", { cy: y, r: 1.8, fill: c })); g.s = s; },
        t(o, T) { T.body.y = 0; both(T, (e) => { e.w = 17; e.h = 23; e.rr = 8.5; e.dx = -2; }); },
        draw(o, t, ts, s, lvl, g) { tr(g.s, 102, 61); op(g.c[1], Math.sin(s * 6) > 0 ? 1 : 0.25); } },
      { name: "Occhioni", desc: "Occhi enormi e lucidi da cucciolo, la testa inclinata: \"per favore?\"",
        t(o, T, ts, s) { T.body.y = 0; T.body.sx = T.body.sy = 1; T.body.rot = -5 + Math.sin(s * 1.5) * 2; both(T, (e) => { e.w = 19; e.h = 25; e.rr = 9.5; e.lb = 0.18; e.tilt = -12; e.lt = 0.08; }); } },
    ],
    error: [
      { name: "Fumo dalla testa", desc: "Sbuffi di fumo salgono da sopra gli occhi: qualcosa si è surriscaldato.",
        init(o, g) { g.p = Array.from({ length: 6 }, () => mk(o.r.vfx, "circle", { r: 2, fill: "#94a3b8", opacity: 0 })); },
        t(o, T, ts, s) { both(T, (e) => { e.h = 4; e.w = 16; e.rr = 2; }); T.body.x = ts < 900 ? Math.sin(ts / 35) * 3 * (1 - ts / 900) : 0; T.sweat = 0; },
        draw(o, t, ts, s, lvl, g) { g.p.forEach((c, i) => { const q = (s * 0.7 + i / 6) % 1; c.setAttribute("cx", f2(60 + (i % 2 ? 8 : -8) + Math.sin(q * 5 + i) * 3)); c.setAttribute("cy", f2(56 - q * 14)); c.setAttribute("r", f2(1.5 + q * 3)); op(c, (1 - q) * 0.7); }); } },
    ],
    sleep: [
      { name: "Sogno", desc: "Dorme e sogna: in una nuvoletta passano un cuore, una stella e una luna.",
        init(o, g) { const c = mk(o.r.vfx, "g", {}); [[-5, 0, 3.6], [0, -2, 4.4], [5, 0, 3.6], [0, 2, 4]].forEach(([x, y, r]) => mk(c, "circle", { cx: x, cy: y, r, fill: "#334155" })); g.i = [mk(c, "path", { d: HEART, fill: "#fb7185", transform: "scale(1.3)" }), mk(c, "path", { d: STAR, fill: "#fde68a", transform: "scale(1.1)" }), mk(c, "path", { d: "M0 -3 a3 3 0 1 0 2.6 4.6 a2.4 2.4 0 1 1 -2.6 -4.6z", fill: "#e2e8f0" })]; g.c = c; g.b = [mk(o.r.vfx, "circle", { cx: 88, cy: 64, r: 1, fill: "#334155" }), mk(o.r.vfx, "circle", { cx: 93, cy: 59, r: 1.5, fill: "#334155" })]; },
        t(o, T) { T.zz = 0; both(T, (e) => { e.lt = 0.88; e.op = 0.5; }); },
        draw(o, t, ts, s, lvl, g) { tr(g.c, 106, 51 + Math.sin(s) * 0.8); const n = Math.floor(s / 1.6) % 3; g.i.forEach((p, i) => op(p, i === n ? 1 : 0)); } },
    ],
  };
  for (const st in V) V[st].forEach((v) => { v.nuova = true; v.lotto = 2; Iris.VARIANTS[st].push(v); });

  /* =============== EASTER EGG (34) =============== */
  const EG = {
    bowling: { nome: "Bowling", dur: 6500, desc: "Una palla da bowling rotola sotto gli occhi e fa strike sui birilli; lui esulta.",
      init(o, g) { g.b = mk(o.r.fx, "circle", { r: 3.6, fill: "#6366f1" }); g.p = [0, 1, 2, 3].map((i) => { const p = mk(o.r.fx, "g", {}); mk(p, "ellipse", { cy: -2.5, rx: 1.3, ry: 3, fill: "#f8fafc" }); mk(p, "rect", { x: -1, y: -3.6, width: 2, height: 0.6, fill: "#ef4444" }); return { n: p, x: 118 + (i % 2) * 4 + (i > 1 ? 7 : 0), y: 76 - (i % 2) * 2 }; }); },
      t(o, T, k, s, a) { const x = -20 + ease(seg(k, 0.05, 0.5)) * 140; look(T, Math.min(x, 120), 74, a); if (k > 0.55) { both(T, (e) => { e.lb = 0.55 * a; }); T.body.y -= Math.abs(Math.sin(s * 9)) * 2 * a; } },
      draw(o, t, k, s, a, g) { const x = -20 + ease(seg(k, 0.05, 0.5)) * 140; g.b.setAttribute("cx", f2(x)); g.b.setAttribute("cy", 75); op(g.b, k < 0.55 ? a : 0); const hit = seg(k, 0.48, 0.65); g.p.forEach((p, i) => { tr(p.n, p.x + hit * (8 + i * 4), p.y - Math.sin(hit * Math.PI) * (6 + i * 2), 1, hit * (60 + i * 40)); op(p.n, a * (1 - seg(k, 0.75, 0.85))); }); } },
    aquilone: { nome: "Aquilone", dur: 8000, desc: "Un aquilone colorato vola in alto con la sua coda, e lui lo tiene d'occhio dondolando.",
      init(o, g) { g.k = mk(o.r.fx, "path", { d: "M0 -5 L4 0 L0 6 L-4 0z", fill: "#f472b6", stroke: "#fde047", "stroke-width": 0.5 }); g.s = mk(o.r.fx, "path", { fill: "none", stroke: "#cbd5e1", "stroke-width": 0.4 }); g.t = mk(o.r.fx, "path", { fill: "none", stroke: "#a78bfa", "stroke-width": 0.8 }); },
      kp(s) { return { x: 108 + Math.sin(s * 0.9) * 10, y: 50 + Math.sin(s * 1.7) * 3 }; },
      t(o, T, k, s, a) { const p = this.kp(s); look(T, p.x, p.y, a); T.body.rot = Math.sin(s * 0.9) * 2 * a; T.L.lb = T.R.lb = 0.25 * a; },
      draw(o, t, k, s, a, g) { const p = this.kp(s); tr(g.k, p.x, p.y, 1, Math.sin(s * 1.7) * 15); g.s.setAttribute("d", `M60 79 Q${f2(p.x - 10)} ${f2(p.y + 20)} ${f2(p.x)} ${f2(p.y + 6)}`); g.t.setAttribute("d", `M${f2(p.x)} ${f2(p.y + 6)} q-3 3 0 6 q3 3 0 6`); [g.k, g.s, g.t].forEach((n) => op(n, a)); } },
    girandola: { nome: "Girandola", dur: 6000, desc: "Una girandola gira col vento, prima piano poi forte; lui ci soffia sopra.",
      init(o, g) { const w = mk(o.r.fx, "g", {}); ["#f87171", "#60a5fa", "#facc15", "#4ade80"].forEach((c, i) => mk(w, "path", { d: "M0 0 L0 -6 Q4 -5 0 0z", fill: c, transform: `rotate(${i * 90})` })); mk(w, "circle", { r: 0.8, fill: "#fff" }); g.w = w; g.st = mk(o.r.fx, "line", { x1: 104, y1: 61, x2: 104, y2: 80, stroke: "#94a3b8", "stroke-width": 0.8 }); g.m = mk(o.r.fx, "circle", { cx: 66, cy: 74.5, r: 1.3, fill: "none", stroke: "currentColor", "stroke-width": 1 }); g.an = 0; },
      t(o, T, k, s, a) { both(T, (e) => { e.dx = 3 * a; e.lt = 0.25 * a; }); },
      draw(o, t, k, s, a, g) { const sp = 2 + ease(seg(k, 0.2, 0.6)) * 30; g.an += sp; tr(g.w, 104, 61, 1, g.an); op(g.w, a); op(g.st, a); op(g.m, k > 0.2 && k < 0.7 ? a : 0); } },
    treno: { nome: "Trenino", dur: 7500, desc: "Un trenino a vapore attraversa la tacca lasciando sbuffi di fumo; lui lo saluta con gli occhi.",
      init(o, g) { const tr0 = mk(o.r.fx, "g", {}); mk(tr0, "rect", { x: -6, y: -5, width: 9, height: 6, rx: 1, fill: "#ef4444" }); mk(tr0, "rect", { x: -2, y: -8, width: 2, height: 3, fill: "#475569" }); mk(tr0, "rect", { x: 4, y: -4, width: 8, height: 5, rx: 1, fill: "#3b82f6" }); mk(tr0, "rect", { x: 13, y: -4, width: 8, height: 5, rx: 1, fill: "#22c55e" }); [-4, 1, 6, 10, 15, 19].forEach((x) => mk(tr0, "circle", { cx: x, cy: 1.6, r: 1.3, fill: "#e2e8f0" })); g.t = tr0; g.p = Array.from({ length: 5 }, () => mk(o.r.fxb, "circle", { r: 2, fill: "#cbd5e1", opacity: 0 })); },
      tx(k) { return 160 - ease(seg(k, 0.05, 0.95)) * 210; },
      t(o, T, k, s, a) { look(T, this.tx(k), 76, a); T.L.lb = T.R.lb = 0.3 * a; },
      draw(o, t, k, s, a, g) { const x = this.tx(k); tr(g.t, x, 76 + (Math.sin(s * 20) > 0 ? 0.3 : 0)); g.p.forEach((c, i) => { const q = (s * 1.2 + i / 5) % 1; c.setAttribute("cx", f2(x - 1 + q * 10)); c.setAttribute("cy", f2(67 - q * 16)); c.setAttribute("r", f2(1 + q * 2.5)); op(c, a * (1 - q) * 0.8); }); } },
    macchinina: { nome: "Macchinina", dur: 6000, desc: "Una macchinina sfreccia da sinistra, frena davanti a lui, suona il clacson e riparte.",
      init(o, g) { const c = mk(o.r.fx, "g", {}); mk(c, "path", { d: "M-8 0 v-3 l3 -1 l2 -3 h6 l3 3 l2 1 v3z", fill: "#facc15" }); mk(c, "path", { d: "M-2.5 -6.4 h2.3 v2.4 h-4z M0.8 -6.4 h2.4 l1.8 2.4 h-4.2z", fill: "#7dd3fc" }); [-5, 4].forEach((x) => mk(c, "circle", { cx: x, cy: 0, r: 1.8, fill: "#1e293b" })); g.c = c; g.h = [0, 1].map(() => mk(o.r.fx, "path", { d: "M0 -3 q2.5 3 0 6", fill: "none", stroke: "#fde047", "stroke-width": 0.9, opacity: 0 })); },
      cx(k) { return k < 0.35 ? -25 + ease(seg(k, 0.02, 0.35)) * 110 : k < 0.6 ? 85 : 85 + Math.pow(seg(k, 0.6, 0.9), 2) * 80; },
      t(o, T, k, s, a) { look(T, this.cx(k), 74, a); if (k > 0.4 && k < 0.6) both(T, (e) => { e.w = 17; e.h = 24; e.rr = 8.5; }); },
      draw(o, t, k, s, a, g) { tr(g.c, this.cx(k), 77); op(g.c, a); const honk = k > 0.42 && k < 0.58 && Math.sin(s * 25) > 0; g.h.forEach((h, i) => { tr(h, 96 + i * 3.5, 72); op(h, honk ? 1 : 0); }); } },
    elicottero: { nome: "Elicottero", dur: 7000, desc: "Un elicotterino arriva, resta sospeso davanti agli occhi con l'elica che gira e poi riparte.",
      init(o, g) { const h = mk(o.r.fx, "g", {}); mk(h, "ellipse", { rx: 5, ry: 3, fill: "#22c55e" }); mk(h, "ellipse", { cx: -2, cy: -0.5, rx: 2, ry: 1.5, fill: "#bae6fd" }); mk(h, "rect", { x: 4, y: -1, width: 7, height: 1.4, fill: "#22c55e" }); mk(h, "path", { d: "M-3 3 h7 M-1 3 v-0.8 M2 3 v-0.8", stroke: "#94a3b8", "stroke-width": 0.6 }); g.r = mk(h, "line", { y1: -3.6, y2: -3.6, stroke: "#e2e8f0", "stroke-width": 0.8 }); g.h = h; },
      pos(k, s) { if (k < 0.3) return { x: -20 + ease(seg(k, 0.02, 0.3)) * 120, y: 52 }; if (k < 0.7) return { x: 100 + Math.sin(s * 2) * 2, y: 52 + Math.sin(s * 3) * 1.5 }; return { x: 100 + ease(seg(k, 0.7, 0.98)) * 60, y: 52 - seg(k, 0.7, 0.98) * 20 }; },
      t(o, T, k, s, a) { const p = this.pos(k, s); look(T, p.x, p.y, a); },
      draw(o, t, k, s, a, g) { const p = this.pos(k, s); tr(g.h, p.x, p.y, 1, k < 0.3 ? -8 : 0); const w = Math.abs(Math.sin(s * 40)) * 7; g.r.setAttribute("x1", f2(-w)); g.r.setAttribute("x2", f2(w)); op(g.h, a); } },
    mongolfiera: { nome: "Mongolfiera", dur: 8000, desc: "Una mongolfiera a strisce sale piano da sotto e se ne va in alto; lui la guarda incantato.",
      init(o, g) { const m = mk(o.r.fx, "g", {}); mk(m, "ellipse", { rx: 6, ry: 7, fill: "#f87171" }); mk(m, "path", { d: "M-2 -7 q-2 7 0 13 M2 -7 q2 7 0 13", fill: "none", stroke: "#fde047", "stroke-width": 1.6 }); mk(m, "path", { d: "M-3 5.5 L-1.6 9 M3 5.5 L1.6 9", stroke: "#94a3b8", "stroke-width": 0.5 }); mk(m, "rect", { x: -1.8, y: 9, width: 3.6, height: 2.6, rx: 0.5, fill: "#a16207" }); g.m = m; },
      pos(k, s) { return { x: 104 + Math.sin(s * 0.8) * 4, y: 95 - ease(seg(k, 0.02, 0.95)) * 70 }; },
      t(o, T, k, s, a) { const p = this.pos(k, s); look(T, p.x, p.y, a); both(T, (e) => { e.lb = 0.25 * a; e.sc = 1 + 0.04 * a; }); },
      draw(o, t, k, s, a, g) { const p = this.pos(k, s); tr(g.m, p.x, p.y, 0.9, Math.sin(s * 0.8) * 4); op(g.m, a); } },
    pianeta: { nome: "Pianeta con l'anello", dur: 7000, desc: "Un pianetino con l'anello gira intorno agli occhi passando davanti e dietro.",
      init(o, g) { const mkp = (par) => { const p = mk(par, "g", {}); mk(p, "circle", { r: 3.2, fill: "#fb923c" }); mk(p, "ellipse", { rx: 5.5, ry: 1.4, fill: "none", stroke: "#fde68a", "stroke-width": 0.8, transform: "rotate(-20)" }); return p; }; g.f = mkp(o.r.fx); g.b = mkp(o.r.fxb); },
      pp(s) { const an = s * 1.6; return { x: 60 + Math.cos(an) * 40, y: 61 + Math.sin(an) * 9, front: Math.sin(an) > 0 }; },
      t(o, T, k, s, a) { const p = this.pp(s); look(T, p.x, p.y, a); },
      draw(o, t, k, s, a, g) { const p = this.pp(s), sc = 0.8 + (p.y - 52) / 18 * 0.4; tr(g.f, p.x, p.y, sc); tr(g.b, p.x, p.y, sc); op(g.f, p.front ? a : 0); op(g.b, p.front ? 0 : a); } },
    lumaca: { nome: "Lumaca", dur: 9000, desc: "Una lumachina attraversa lentissima il fondo da sinistra a destra; gli occhi la seguono con santa pazienza, e sbadiglia.",
      init(o, g) { const l = mk(o.r.fx, "g", {}); mk(l, "path", { d: "M-6 0 h10 q2 0 2 -2 l1 -3 M5 -2 l1.5 -3.5", fill: "none", stroke: "#a3e635", "stroke-width": 1.6, "stroke-linecap": "round" }); mk(l, "circle", { cx: -1, cy: -3.2, r: 3.4, fill: "#d97706" }); mk(l, "path", { d: "M-1 -3.2 m-1.6 0 a1.6 1.6 0 1 1 1.6 1.6", fill: "none", stroke: "#fde68a", "stroke-width": 0.6 }); g.l = l; },
      lx(k) { return -12 + k * 140; }, // va verso destra, dove guarda la testa
      t(o, T, k, s, a) { look(T, this.lx(k), 76, a); both(T, (e) => { e.lt = 0.35 * a; }); const y = k > 0.5 && k < 0.65 ? Math.sin(seg(k, 0.5, 0.65) * Math.PI) : 0; T.L.h += 5 * y; T.R.h += 5 * y; T.L.lt = T.R.lt = Math.max(T.L.lt, 0.6 * y); },
      draw(o, t, k, s, a, g) { tr(g.l, this.lx(k), 77.5, 0.9); op(g.l, a); } },
    ragnetto: { nome: "Ragnetto", dur: 6500, desc: "Un ragnetto scende appeso al suo filo di lato, accanto all'occhio destro: lui si scansa spaventato, poi il ragno risale.",
      init(o, g) { g.f = mk(o.r.fx, "line", { x1: 96, y1: 40, x2: 96, stroke: "#e2e8f0", "stroke-width": 0.4 }); const r = mk(o.r.fx, "g", {}); mk(r, "path", { d: "M-2 -1 l-3 -2 M-2 0 l-3.5 0 M-2 1 l-3 2 M2 -1 l3 -2 M2 0 l3.5 0 M2 1 l3 2", stroke: "#94a3b8", "stroke-width": 0.7 }); mk(r, "circle", { r: 2.4, fill: "#64748b" }); mk(r, "circle", { cx: -0.8, cy: -0.6, r: 0.5, fill: "#fff" }); mk(r, "circle", { cx: 0.8, cy: -0.6, r: 0.5, fill: "#fff" }); g.r = r; },
      ry(k, s) { return 40 + ease(seg(k, 0.05, 0.35)) * 21 * (1 - ease(seg(k, 0.75, 0.95))) + Math.sin(s * 3) * 0.8; },
      t(o, T, k, s, a) { const y = this.ry(k, s); if (k > 0.3 && k < 0.8) { both(T, (e) => { e.w = 12; e.h = 24; e.sc = 0.85; e.dx = -4; }); T.body.x = -3 + Math.sin(s * 40) * 0.5; T.body.rot = 4; T.sweat = 1; } else look(T, 96, y, a); },
      draw(o, t, k, s, a, g) { const y = this.ry(k, s); g.f.setAttribute("y2", f2(y)); tr(g.r, 96, y); op(g.r, a); op(g.f, a); } },
    coccinella: { nome: "Coccinella", dur: 7000, desc: "Una coccinella cammina sull'occhio sinistro, lui la guarda strabico, poi lei apre le ali e vola via.",
      init(o, g) { const c = mk(o.r.fx, "g", {}); g.w = [mk(c, "path", { d: "M0 -2.4 A2.6 2.6 0 0 0 0 2.6 z", fill: "#ef4444" }), mk(c, "path", { d: "M0 -2.4 A2.6 2.6 0 0 1 0 2.6 z", fill: "#ef4444" })]; mk(c, "circle", { cy: -2.6, r: 1.2, fill: "#111" }); [[-1.2, 0], [1.2, 0.8], [-0.9, 1.6], [1, -0.8]].forEach(([x, y]) => mk(c, "circle", { cx: x, cy: y, r: 0.5, fill: "#111" })); g.c = c; },
      pos(k) { if (k < 0.55) { const q = seg(k, 0.05, 0.55); return { x: 40 + q * 10, y: 76 - q * 22, rot: 15 }; } const q = seg(k, 0.65, 0.95); return { x: 50 + q * 80, y: 54 - q * 20 - Math.sin(q * 12) * 2, rot: 60 }; },
      t(o, T, k, s, a) { const p = this.pos(k); look(T, p.x, p.y, a); if (k > 0.3 && k < 0.65) { T.L.dx = 3; T.R.dx = -4; T.L.dy = T.R.dy = -2; } },
      draw(o, t, k, s, a, g) { const p = this.pos(k); tr(g.c, p.x, p.y, 1, p.rot); const open = k > 0.6 ? 35 + Math.sin(s * 30) * 10 : 0; g.w[0].setAttribute("transform", `rotate(${f2(-open)} 0 -2)`); g.w[1].setAttribute("transform", `rotate(${f2(open)} 0 -2)`); op(g.c, a); } },
    uccellino: { nome: "Uccellino", dur: 8000, desc: "Un uccellino si posa sopra la tacca, cinguetta qualche nota e vola via.",
      init(o, g) { const b = mk(o.r.fx, "g", {}); mk(b, "ellipse", { rx: 3.6, ry: 2.8, fill: "#60a5fa" }); mk(b, "circle", { cx: 2.8, cy: -1.8, r: 1.9, fill: "#60a5fa" }); mk(b, "path", { d: "M4.4 -1.9 l1.8 0.5 l-1.8 0.6z", fill: "#fb923c" }); mk(b, "circle", { cx: 3.2, cy: -2.2, r: 0.4, fill: "#111" }); g.w = mk(b, "path", { d: "M-1 -1 q-3 -3 -4 0z", fill: "#3b82f6" }); g.b = b; g.n = [0, 1].map(() => mk(o.r.fx, "path", { d: "M1.6 -5 V1.4 A1.8 1.4 0 1 1 0.2 0.1 V-5 Z", fill: "#bae6fd", opacity: 0 })); },
      pos(k, s) { if (k < 0.25) { const q = ease(seg(k, 0.02, 0.25)); return { x: -20 + q * 92, y: 30 + q * 17 }; } if (k < 0.75) return { x: 72, y: 47 + (Math.sin(s * 8) > 0.7 ? -1 : 0) }; const q = seg(k, 0.75, 0.98); return { x: 72 + q * 80, y: 47 - q * 25 }; },
      t(o, T, k, s, a) { const p = this.pos(k, s); look(T, p.x, p.y, a); if (k > 0.3 && k < 0.7) both(T, (e) => { e.lb = 0.4 * a; }); },
      draw(o, t, k, s, a, g) { const p = this.pos(k, s), fly = k < 0.25 || k > 0.75; tr(g.b, p.x, p.y); g.w.setAttribute("transform", fly ? `scale(1 ${f2(Math.sin(s * 30))})` : ""); op(g.b, a); g.n.forEach((n, i) => { const q = (s * 0.8 + i / 2) % 1; tr(n, 80 + q * 12, 46 - q * 6, 0.6); op(n, k > 0.3 && k < 0.7 ? Math.sin(q * Math.PI) : 0); }); } },
    medusa: { nome: "Medusa", dur: 8000, desc: "Una medusa trasparente sale pulsando, con i tentacoli che ondeggiano; gli occhi la seguono incantati.",
      init(o, g) { const m = mk(o.r.fx, "g", {}); g.top = mk(m, "path", { d: "M-5 0 a5 5 0 0 1 10 0z", fill: "#e879f9", opacity: 0.75 }); g.t = [-3, -1, 1, 3].map((x) => mk(m, "path", { fill: "none", stroke: "#f0abfc", "stroke-width": 0.6 })); g.m = m; },
      pos(k, s) { return { x: 100 + Math.sin(s * 0.7) * 8, y: 90 - ease(seg(k, 0.03, 0.97)) * 60 }; },
      t(o, T, k, s, a) { const p = this.pos(k, s); look(T, p.x, p.y, a); both(T, (e) => { e.sc = 1 + 0.05 * a; e.lb = 0.15 * a; }); },
      draw(o, t, k, s, a, g) { const p = this.pos(k, s), pu = Math.sin(s * 4); tr(g.m, p.x, p.y); g.top.setAttribute("transform", `scale(${f2(1 + pu * 0.12)} ${f2(1 - pu * 0.12)})`); g.t.forEach((n, i) => { const x = [-3, -1, 1, 3][i]; n.setAttribute("d", `M${x} 0 q${f2(Math.sin(s * 5 + i) * 2)} 3 0 6 q${f2(-Math.sin(s * 5 + i) * 2)} 3 0 6`); }); op(g.m, a); } },
    occhistella: { nome: "Occhi a stella", dur: 5500, desc: "Resta a bocca aperta: gli occhi diventano due stelle che brillano.",
      init(o, g) { g.s = [46, 74].map((x) => mk(o.r.fx, "path", { d: STAR, fill: "#fde047", opacity: 0 })); g.m = mk(o.r.fx, "ellipse", { cx: 60, cy: 75, rx: 2, ry: 2.6, fill: "currentColor", opacity: 0 }); },
      t(o, T, k, s, a) { const on = seg(k, 0.1, 0.18) * (1 - seg(k, 0.82, 0.9)); both(T, (e) => { e.sc = 1 - on; }); T.body.y -= Math.abs(Math.sin(s * 5)) * on; },
      draw(o, t, k, s, a, g) { const on = seg(k, 0.1, 0.18) * (1 - seg(k, 0.82, 0.9)); g.s.forEach((p, i) => { tr(p, i ? 74 : 46, 61, (3.4 + Math.sin(s * 8 + i) * 0.4) * on, s * 40 * (i ? -1 : 1)); op(p, on); }); op(g.m, on); } },
    dollari: { nome: "Occhi a dollaro", dur: 5500, desc: "Gli occhi diventano due simboli del dollaro che girano come una slot machine: \"ka-ching!\"",
      init(o, g) { g.d = [46, 74].map((x) => txt(o.r.fx, "$", { x, y: 62, "font-size": 17, fill: "#4ade80", opacity: 0 })); g.c = Array.from({ length: 5 }, () => mk(o.r.fx, "circle", { r: 1.8, fill: "#facc15", stroke: "#a16207", "stroke-width": 0.4, opacity: 0 })); },
      t(o, T, k, s, a) { const on = seg(k, 0.08, 0.15) * (1 - seg(k, 0.85, 0.92)); both(T, (e) => { e.sc = 1 - on; }); },
      draw(o, t, k, s, a, g) { const on = seg(k, 0.08, 0.15) * (1 - seg(k, 0.85, 0.92)), spin = k < 0.4; g.d.forEach((d, i) => { d.textContent = spin ? "$€£¥"[Math.floor(s * 12 + i) % 4] : "$"; d.setAttribute("transform", spin ? `translate(0 ${f2(Math.sin(s * 30) * 1)})` : ""); op(d, on); }); g.c.forEach((c, i) => { const q = seg(k, 0.4 + i * 0.05, 0.75 + i * 0.05); c.setAttribute("cx", f2(60 + (i - 2) * 8)); c.setAttribute("cy", f2(45 + q * 36)); op(c, q > 0 && q < 1 ? a : 0); }); } },
    nerd: { nome: "Occhiali da secchione", dur: 6000, desc: "Spuntano degli occhialoni tondi: se li sistema sul naso con aria saputa.",
      init(o, g) { const gl = mk(o.r.fx, "g", { fill: "none", stroke: "#e2e8f0", "stroke-width": 1.3 }); mk(gl, "circle", { cx: 46, cy: 61, r: 11 }); mk(gl, "circle", { cx: 74, cy: 61, r: 11 }); mk(gl, "path", { d: "M57 59 q3 -2 6 0 M35 58 l-8 -3 M85 58 l8 -3" }); g.g = gl; },
      t(o, T, k, s, a) { both(T, (e) => { e.lt = 0.25 * a; e.sc = 0.85; e.dy = -1; }); T.R.tilt = -8 * a; },
      draw(o, t, k, s, a, g) { const push = k > 0.45 && k < 0.6 ? -Math.sin(seg(k, 0.45, 0.6) * Math.PI) * 2.5 : 0, drop = (1 - ease(seg(k, 0.05, 0.2))) * -20; g.g.setAttribute("transform", `translate(0 ${f2(drop + push + 1)})`); op(g.g, a); } },
    festa: { nome: "Cappellino da festa", dur: 6500, desc: "Un cappellino a punta in testa e una lingua di Menelik che si srotola: festa!",
      init(o, g) { const h = mk(o.r.fx, "g", {}); mk(h, "path", { d: "M-6 0 L0 -12 L6 0z", fill: "#a78bfa" }); mk(h, "path", { d: "M-4 -4 l8 0 M-2 -8 l4 0", stroke: "#fde047", "stroke-width": 1 }); mk(h, "circle", { cy: -12, r: 1.6, fill: "#fde047" }); g.h = h; g.b = mk(o.r.fx, "path", { fill: "none", stroke: "#f472b6", "stroke-width": 2, "stroke-linecap": "round" }); },
      t(o, T, k, s, a) { both(T, (e) => { e.lb = 0.5 * a; }); T.body.y -= Math.abs(Math.sin(s * 6)) * 1.5 * a; T.body.rot = Math.sin(s * 3) * 3 * a; },
      draw(o, t, k, s, a, g) { tr(g.h, 72, 52 - (1 - ease(seg(k, 0.03, 0.15))) * 15, 0.8, 15); op(g.h, a); const ext = Math.max(0, Math.sin(s * 3)) * (k > 0.2 && k < 0.9 ? 1 : 0); g.b.setAttribute("d", ext > 0.05 ? `M60 75 q${f2(8 * ext)} ${f2(-4 * ext)} ${f2(16 * ext)} 0 q${f2(6 * ext)} 4 ${f2(10 * ext)} -1` : "M60 75 a1.5 1.5 0 1 0 0.1 0"); op(g.b, a); } },
    corona: { nome: "Corona", dur: 6000, desc: "Gli scende in testa una coroncina d'oro: alza il mento con aria regale.",
      init(o, g) { const c = mk(o.r.fx, "g", {}); mk(c, "path", { d: "M-8 0 L-8 -6 L-4 -2 L0 -8 L4 -2 L8 -6 L8 0z", fill: "#fbbf24" }); [-8, 0, 8].forEach((x, i) => mk(c, "circle", { cx: x, cy: [-6, -8, -6][i], r: 1, fill: "#f87171" })); g.c = c; },
      t(o, T, k, s, a) { both(T, (e) => { e.lt = 0.3 * a; e.dy = -2 * a; e.lb = 0.15 * a; }); T.body.rot = -3 * a; },
      draw(o, t, k, s, a, g) { tr(g.c, 60, 50 - (1 - ease(seg(k, 0.05, 0.25))) * 20, 0.9, -3); op(g.c, a); } },
    supereroe: { nome: "Supereroe", dur: 6000, desc: "Una mascherina da supereroe sugli occhi e uno sguardo deciso verso l'orizzonte.",
      init(o, g) { g.m = mk(o.r.fxb, "path", { d: "M30 55 q16 -6 30 0 q14 -6 30 0 q2 8 -4 14 q-12 4 -18 -2 q-8 -4 -16 0 q-6 6 -18 2 q-6 -6 -4 -14z", fill: "#ef4444" }); g.t = mk(o.r.fxb, "path", { fill: "none", stroke: "#ef4444", "stroke-width": 2, "stroke-linecap": "round" }); },
      t(o, T, k, s, a) { both(T, (e) => { e.lt = 0.32 * a; e.tilt = 10 * a; e.h = 18; e.dx = 3 * a; }); T.body.rot = -2 * a; },
      draw(o, t, k, s, a, g) { op(g.m, a); op(g.t, a); g.t.setAttribute("d", `M30 58 q-8 ${f2(Math.sin(s * 9) * 3)} -16 ${f2(2 + Math.sin(s * 7) * 3)}`); } },
    ninja: { nome: "Ninja", dur: 6500, desc: "Una fascia nera sugli occhi con le code che sventolano: sguardo da ninja, poi sparisce in un lampo.",
      init(o, g) { g.f = mk(o.r.fxb, "rect", { x: 28, y: 52, width: 64, height: 18, rx: 4, fill: "#1e293b" }); g.c = [0, 1].map(() => mk(o.r.fxb, "path", { fill: "none", stroke: "#1e293b", "stroke-width": 2.4, "stroke-linecap": "round" })); },
      t(o, T, k, s, a) { both(T, (e) => { e.h = 8; e.w = 15; e.rr = 3; e.tilt = 12; e.lt = 0.1; }); const dash = seg(k, 0.8, 0.86); both(T, (e) => { e.dx = dash * 60; }); },
      draw(o, t, k, s, a, g) { op(g.f, a * (1 - seg(k, 0.8, 0.86))); g.c.forEach((c, i) => { c.setAttribute("d", `M92 ${58 + i * 4} q8 ${f2(Math.sin(s * 10 + i) * 3)} 16 ${f2(Math.sin(s * 8 + i) * 4 + i * 2)}`); op(c, a * (1 - seg(k, 0.8, 0.86))); }); } },
    puzzle: { nome: "Puzzle", dur: 7000, desc: "Quattro pezzi di puzzle arrivano dai lati e si incastrano; lui fa un sorriso soddisfatto.",
      init(o, g) { const cols = ["#60a5fa", "#f472b6", "#4ade80", "#facc15"]; g.p = cols.map((c, i) => mk(o.r.fx, "rect", { width: 6, height: 6, rx: 1, fill: c, opacity: 0 })); g.from = [[-25, 45], [150, 45], [-25, 80], [150, 80]]; g.to = [[101, 55], [107, 55], [101, 61], [107, 61]]; },
      t(o, T, k, s, a) { look(T, 106, 60, a); if (k > 0.7) both(T, (e) => { e.lb = 0.5 * a; }); },
      draw(o, t, k, s, a, g) { g.p.forEach((p, i) => { const q = ease(seg(k, 0.05 + i * 0.12, 0.2 + i * 0.12)), [fx, fy] = g.from[i], [tx, ty] = g.to[i]; p.setAttribute("x", f2(fx + (tx - fx) * q)); p.setAttribute("y", f2(fy + (ty - fy) * q)); op(p, a); }); } },
    rubik: { nome: "Cubo di Rubik", dur: 7000, desc: "Un cubo di Rubik gira le sue file a tutta velocità finché i colori tornano a posto.",
      init(o, g) { g.c = []; for (let r = 0; r < 3; r++) for (let c = 0; c < 3; c++) g.c.push(mk(o.r.fx, "rect", { x: 98 + c * 4, y: 55 + r * 4, width: 3.6, height: 3.6, rx: 0.6 })); g.cols = ["#ef4444", "#3b82f6", "#22c55e", "#facc15", "#f97316", "#f8fafc"]; g.last = 0; },
      t(o, T, k, s, a) { look(T, 104, 61, a); both(T, (e) => { e.lt = (k < 0.75 ? 0.25 : 0) * a; e.lb = (k > 0.75 ? 0.5 : 0) * a; }); },
      draw(o, t, k, s, a, g) { if (k < 0.75 && t - g.last > 150) { g.last = t; g.c.forEach((c) => c.setAttribute("fill", g.cols[Math.floor(Math.random() * 6)])); } if (k >= 0.75) g.c.forEach((c) => c.setAttribute("fill", "#22c55e")); g.c.forEach((c) => op(c, a)); } },
    domino: { nome: "Domino", dur: 6500, desc: "Una fila di tessere del domino cade una dopo l'altra sotto gli occhi, che seguono l'onda.",
      init(o, g) { g.d = Array.from({ length: 10 }, (_, i) => ({ n: mk(o.r.fx, "rect", { x: -1, y: -7, width: 2, height: 7, rx: 0.4, fill: "#f8fafc" }), x: 22 + i * 8 })); },
      t(o, T, k, s, a) { const x = 22 + seg(k, 0.1, 0.8) * 72; look(T, x, 74, a); },
      draw(o, t, k, s, a, g) { g.d.forEach((d, i) => { const q = ease(seg(k, 0.1 + i * 0.07, 0.17 + i * 0.07)); tr(d.n, d.x, 79, 1, q * 72); op(d.n, a); }); } },
    pendolo: { nome: "Pendolo", dur: 6000, desc: "Tic tac: gli occhi vanno a destra e a sinistra a scatti come il pendolo di un vecchio orologio.",
      init(o, g) { g.l = mk(o.r.fxb, "line", { x1: 60, y1: 40, stroke: "#94a3b8", "stroke-width": 0.6 }); g.b = mk(o.r.fxb, "circle", { r: 2.4, fill: "#fbbf24" }); },
      t(o, T, k, s, a) { const side = Math.floor(s * 2) % 2 ? 1 : -1; both(T, (e) => { e.dx = side * 5 * a; }); T.body.rot = side * 2 * a; },
      draw(o, t, k, s, a, g) { const an = Math.sin(s * Math.PI * 2) * 0.5, x = 60 + Math.sin(an) * 36, y = 40 + Math.cos(an) * 36; g.l.setAttribute("x2", f2(x)); g.l.setAttribute("y2", f2(y)); g.b.setAttribute("cx", f2(x)); g.b.setAttribute("cy", f2(y)); op(g.l, a); op(g.b, a); } },
    scambio: { nome: "Scambio di posto", dur: 5000, desc: "Gli occhi si scambiano di posto saltando uno sopra l'altro, poi tornano come prima.",
      t(o, T, k, s, a) { const q = ease(seg(k, 0.15, 0.4)) - ease(seg(k, 0.6, 0.85)); T.L.dx = 28 * q; T.R.dx = -28 * q; T.L.dy = -Math.sin(q * Math.PI) * 9; T.R.dy = Math.sin(q * Math.PI) * 6; T.L.sc = 1 + Math.sin(q * Math.PI) * 0.1; T.R.sc = 1 - Math.sin(q * Math.PI) * 0.15; if (k > 0.4 && k < 0.6) { T.L.lb = T.R.lb = 0.4; } } },
    corda: { nome: "Salto della corda", dur: 7000, desc: "Una corda gira intorno agli occhi e loro saltano a tempo per non inciampare.",
      init(o, g) { g.f = mk(o.r.fx, "path", { fill: "none", stroke: "#f472b6", "stroke-width": 1.2 }); g.b = mk(o.r.fxb, "path", { fill: "none", stroke: "#f472b6", "stroke-width": 1.2 }); },
      t(o, T, k, s, a) { const an = s * 6, jump = Math.max(0, -Math.sin(an)) * a; T.body.y -= jump * 6; T.body.sy = 1 + (1 - jump) * 0.03 * a; both(T, (e) => { e.lb = 0.3 * a; }); },
      draw(o, t, k, s, a, g) { const an = s * 6, y = 61 + Math.sin(an) * 20, front = Math.cos(an) > 0, d = `M26 61 Q60 ${f2(y + (y - 61))} 94 61`; g.f.setAttribute("d", d); g.b.setAttribute("d", d); op(g.f, front ? a : 0); op(g.b, front ? 0 : a); } },
    hulahoop: { nome: "Hula hoop", dur: 6500, desc: "Un cerchio gira intorno agli occhi mentre lui ondeggia per tenerlo su.",
      init(o, g) { g.f = mk(o.r.fx, "path", { fill: "none", stroke: "#4ade80", "stroke-width": 1.6 }); g.b = mk(o.r.fxb, "path", { fill: "none", stroke: "#4ade80", "stroke-width": 1.6 }); },
      t(o, T, k, s, a) { T.body.x = Math.sin(s * 8) * 2 * a; T.body.rot = Math.sin(s * 8 + 1) * 2 * a; both(T, (e) => { e.lb = 0.35 * a; }); },
      draw(o, t, k, s, a, g) { const cx = 60 + Math.sin(s * 8) * 4, rx = 30, ry = 5, y = 70; g.f.setAttribute("d", `M${f2(cx - rx)} ${y} A${rx} ${ry} 0 0 0 ${f2(cx + rx)} ${y}`); g.b.setAttribute("d", `M${f2(cx - rx)} ${y} A${rx} ${ry} 0 0 1 ${f2(cx + rx)} ${y}`); op(g.f, a); op(g.b, a * 0.6); } },
    singhiozzo: { nome: "Singhiozzo", dur: 6000, desc: "Ha il singhiozzo: ogni tanto un sobbalzo improvviso con un piccolo \"hic!\".",
      init(o, g) { g.t = txt(o.r.fx, "hic!", { x: 100, y: 52, "font-size": 6, fill: "#e2e8f0", opacity: 0 }); },
      hic(s) { const q = (s % 1.3) / 1.3; return q < 0.12 ? Math.sin((q / 0.12) * Math.PI) : 0; },
      t(o, T, k, s, a) { const h = this.hic(s) * a; T.body.y -= h * 5; both(T, (e) => { e.w = 15 + h * 2; e.h = 21 + h * 4; e.lt = 0.15 * (1 - h) * a; }); },
      draw(o, t, k, s, a, g) { const q = (s % 1.3) / 1.3; tr(g.t, 0, -q * 4); op(g.t, q < 0.45 ? a * (1 - q / 0.45) : 0); } },
    caldo: { nome: "Che caldo", dur: 7000, desc: "Un sole che picchia, gli occhi che si sciolgono un po' e un ventaglio che sventola.",
      init(o, g) { const sun = mk(o.r.fxb, "g", {}); mk(sun, "circle", { r: 4.5, fill: "#fde047" }); for (let i = 0; i < 8; i++) mk(sun, "rect", { x: -0.5, y: -8, width: 1, height: 2.4, rx: 0.5, fill: "#fde047", transform: `rotate(${i * 45})` }); g.s = sun; const f = mk(o.r.fx, "g", {}); for (let i = 0; i < 5; i++) mk(f, "path", { d: "M0 0 L-3 -8 L3 -8z", fill: i % 2 ? "#f472b6" : "#f9a8d4", transform: `rotate(${-40 + i * 20})` }); g.f = f; },
      t(o, T, k, s, a) { const m = seg(k, 0.1, 0.5) * a; both(T, (e) => { e.h = 21 - m * 6; e.dy = m * 3; e.w = 15 + m * 2; e.lt = 0.25 * m; }); T.sweat = m > 0.3 ? 1 : 0; },
      draw(o, t, k, s, a, g) { tr(g.s, -12, 50, 1, s * 20); op(g.s, a); tr(g.f, 100, 74, 1, Math.sin(s * 10) * 25); op(g.f, k > 0.4 ? a : 0); } },
  };
  for (const id in EG) { EG[id].nuova = true; EG[id].lotto = 2; EG[id].auto = true; Iris.EGGS[id] = EG[id]; }
  Iris.NUOVE.eggs = Iris.NUOVE.eggs.concat(Object.keys(EG));

  /* =============== CONCEPT: LE MANI (5) ===============
     Le mani sono due palline tonde del colore degli occhi, senza braccia (come nei cartoni con le mani "staccate"). */
  const hands = (o, g) => { g.h = [0, 1].map(() => mk(o.r.fx, "circle", { r: 4, fill: "currentColor" })); g.hs = [0, 1].map(() => mk(o.r.fx, "circle", { r: 1.1, fill: "#fff", opacity: 0.3 })); };
  const putHand = (g, i, x, y, a, sc = 1) => { g.h[i].setAttribute("cx", f2(x)); g.h[i].setAttribute("cy", f2(y)); g.h[i].setAttribute("r", f2(4 * sc)); op(g.h[i], a); g.hs[i].setAttribute("cx", f2(x - 1.3 * sc)); g.hs[i].setAttribute("cy", f2(y - 1.3 * sc)); op(g.hs[i], a * 0.3); };
  const MA = {
    mano_saluto: { nome: "Ciao con la mano", dur: 5500, desc: "Spunta una manina accanto agli occhi e saluta muovendosi avanti e indietro; occhi sorridenti.",
      init: hands,
      t(o, T, k, s, a) { both(T, (e) => { e.lb = 0.5 * a; e.dx = -2 * a; }); T.body.rot = -3 * a; },
      draw(o, t, k, s, a, g) { const up = ease(seg(k, 0.05, 0.2)) * (1 - ease(seg(k, 0.85, 0.97))); putHand(g, 0, 96 + Math.sin(s * 10) * 4, 82 - up * 22, a); putHand(g, 1, 0, 0, 0); } },
  };
  for (const id in MA) { MA[id].nuova = true; MA[id].concept = true; MA[id].auto = false; Iris.EGGS[id] = MA[id]; }
  Iris.NUOVE.mani = Object.keys(MA);

  /* =============== REAZIONI NUOVE (6) ===============
     Partono per qualcosa che fai tu (campo "quando"); non arrivano mai a sorpresa. */
  const RE = {
    carezza: { nome: "Carezza", quando: "passi il mouse piano avanti e indietro sugli occhi", dur: 4500, desc: "Chiude gli occhi beato, dondola e salgono due cuoricini, come un gatto che fa le fusa.",
      init(o, g) { g.h = [0, 1].map(() => mk(o.r.fx, "path", { d: HEART, fill: "#fb7185", opacity: 0 })); g.p = [0, 1].map(() => mk(o.r.fx, "path", { d: "M0 -2 q1.6 2 0 4", fill: "none", stroke: "currentColor", "stroke-width": 0.8, opacity: 0 })); },
      t(o, T, k, s, a) { both(T, (e) => { e.lb = 0.62 * a; e.lt = 0.2 * a; }); T.body.rot = Math.sin(s * 2.5) * 4 * a; T.body.y += Math.sin(s * 40) * 0.2 * a; },
      draw(o, t, k, s, a, g) { g.h.forEach((h, i) => { const q = (s * 0.5 + i / 2) % 1; tr(h, 86 + i * 8 + Math.sin(q * 6) * 2, 68 - q * 22, 1 + q * 0.5); op(h, a * Math.sin(q * Math.PI)); }); g.p.forEach((p, i) => { tr(p, i ? 92 : 28, 61, 1, i ? 0 : 180); op(p, a * (Math.sin(s * 20 + i) > 0 ? 0.8 : 0.2)); }); } },
    vento: { nome: "Controvento", quando: "lo trascini molto veloce", dur: 2500, desc: "Strizza gli occhi come col vento in faccia, si piega all'indietro e dietro passano le righe della velocità.",
      init(o, g) { g.l = Array.from({ length: 6 }, (_, i) => mk(o.r.fxb, "line", { stroke: "#e2e8f0", "stroke-width": 0.8, "stroke-linecap": "round", opacity: 0 })); },
      t(o, T, k, s, a) { both(T, (e) => { e.lt = 0.45 * a; e.lb = 0.2 * a; e.w = 16; e.dx = 3 * a; }); T.body.rot = 6 * a; T.body.x = Math.sin(s * 30) * 0.5 * a; },
      draw(o, t, k, s, a, g) { g.l.forEach((l, i) => { const q = (s * 2.2 + prand(i)) % 1, y = 47 + prand(i, 1) * 28, x = 120 - q * 160; l.setAttribute("x1", f2(x)); l.setAttribute("x2", f2(x + 14)); l.setAttribute("y1", f2(y)); l.setAttribute("y2", f2(y)); op(l, a * 0.7); }); } },
    atterraggio: { nome: "Atterraggio", quando: "lo lasci andare dopo averlo trascinato", dur: 1800, desc: "Arriva giù schiacciandosi come una pallina di gomma, fa due rimbalzi e solleva un po' di polvere.",
      init(o, g) { g.d = [0, 1, 2, 3].map(() => mk(o.r.fx, "circle", { r: 1.5, fill: "#94a3b8", opacity: 0 })); },
      t(o, T, k, s, a) { const b1 = Math.max(0, Math.sin(seg(k, 0.15, 0.5) * Math.PI)) * 6, b2 = Math.max(0, Math.sin(seg(k, 0.55, 0.8) * Math.PI)) * 2.5, sq = k < 0.15 ? Math.sin((k / 0.15) * Math.PI) : k > 0.5 && k < 0.58 ? Math.sin(seg(k, 0.5, 0.58) * Math.PI) * 0.6 : 0; T.body.y -= b1 + b2; T.body.sy = 1 - sq * 0.12; T.body.sx = 1 + sq * 0.1; both(T, (e) => { e.lt = sq * 0.3; e.lb = (k > 0.8 ? 0.4 : 0) * a; }); },
      draw(o, t, k, s, a, g) { const q = seg(k, 0, 0.4); g.d.forEach((d, i) => { const sd = i < 2 ? -1 : 1, x = 60 + sd * (22 + q * (8 + (i % 2) * 8)); d.setAttribute("cx", f2(x)); d.setAttribute("cy", f2(77 - q * 4 - (i % 2) * 2)); d.setAttribute("r", f2(1 + q * 2)); op(d, (1 - q) * 0.7 * a); }); } },
    risveglio: { nome: "Svegliato di colpo", quando: "lo clicchi mentre dorme", dur: 3200, desc: "Dormiva: al clic fa un salto con gli occhi spalancati e un punto esclamativo, poi sbatte le palpebre un paio di volte per svegliarsi.",
      init(o, g) { g.e = txt(o.r.fx, "!", { x: 92, y: 52, "font-size": 11, fill: "#fde047", opacity: 0 }); },
      t(o, T, k, s, a) { if (k < 0.15) { both(T, (e) => { e.lt = 0.86; e.op = 0.5; }); return; } if (k < 0.5) { both(T, (e) => { e.w = 18; e.h = 26; e.rr = 9; }); T.body.y -= Math.sin(seg(k, 0.15, 0.3) * Math.PI) * 6; } else { const bl = Math.abs(Math.sin(seg(k, 0.5, 0.9) * Math.PI * 3)); both(T, (e) => { e.lt = bl * 0.8; }); } },
      draw(o, t, k, s, a, g) { tr(g.e, 0, -Math.sin(seg(k, 0.15, 0.3) * Math.PI) * 3); op(g.e, k > 0.15 && k < 0.5 ? 1 : 0); } },
    posta: { nome: "Posta in arrivo", quando: "arriva una risposta mentre l'isola è chiusa", dur: 4000, desc: "Una busta vola dentro la tacca e si ferma accanto agli occhi, che la guardano curiosi; la busta saltella per farsi aprire.",
      init(o, g) { const e = mk(o.r.fx, "g", {}); mk(e, "rect", { x: -5, y: -3.5, width: 10, height: 7, rx: 1, fill: "#f8fafc" }); mk(e, "path", { d: "M-5 -3.5 L0 0.8 L5 -3.5", fill: "none", stroke: "#94a3b8", "stroke-width": 0.8 }); g.dot = mk(e, "circle", { cx: 4.8, cy: -3.4, r: 1.5, fill: "#ef4444" }); g.e = e; },
      pos(k, s) { const q = ease(seg(k, 0.02, 0.3)); return { x: 150 - q * 50, y: 46 + q * 15 - Math.sin(q * Math.PI) * 6 + (k > 0.35 ? -Math.abs(Math.sin(s * 6)) * 2 : 0) }; },
      t(o, T, k, s, a) { const p = this.pos(k, s); look(T, p.x, p.y, a); if (k > 0.35) { T.L.h = 18; T.R.h = 24; T.R.w = 16.5; T.body.rot = -4 * a; } },
      draw(o, t, k, s, a, g) { const p = this.pos(k, s); tr(g.e, p.x, p.y, 1, k < 0.3 ? -20 * (1 - seg(k, 0, 0.3)) : Math.sin(s * 12) * 4 * (k > 0.35 ? 1 : 0)); op(g.e, a); op(g.dot, k > 0.35 ? 1 : 0); } },
    bentornato: { nome: "Bentornato", quando: "torni al PC dopo più di mezz'ora", dur: 4000, desc: "Ti vede tornare: si stiracchia, fa un saltello e ti saluta con la manina, con qualche stellina intorno.",
      init(o, g) { g.h = mk(o.r.fx, "circle", { r: 4, fill: "currentColor", opacity: 0 }); g.st = [[30, 50], [90, 48], [94, 72]].map(([x, y]) => ({ n: mk(o.r.fx, "path", { d: STAR, fill: "#fde68a", opacity: 0 }), x, y })); },
      t(o, T, k, s, a) { if (k < 0.3) { const st = Math.sin(seg(k, 0, 0.3) * Math.PI); both(T, (e) => { e.h = 21 + st * 6; e.lt = st * 0.5; }); T.body.sy = 1 + st * 0.04; } else { both(T, (e) => { e.lb = 0.55 * a; e.dx = -2 * a; }); if (k < 0.45) T.body.y -= Math.sin(seg(k, 0.3, 0.45) * Math.PI) * 5; } },
      draw(o, t, k, s, a, g) { const up = ease(seg(k, 0.35, 0.5)) * (1 - ease(seg(k, 0.88, 0.98))); g.h.setAttribute("cx", f2(96 + Math.sin(s * 10) * 4)); g.h.setAttribute("cy", f2(84 - up * 22)); op(g.h, a); g.st.forEach((p, i) => { const q = seg(k, 0.35 + i * 0.08, 0.6 + i * 0.08); tr(p.n, p.x, p.y, Math.sin(q * Math.PI) * 1.3, s * 90); op(p.n, q > 0 && q < 1 ? a : 0); }); } },
  };
  for (const id in RE) { RE[id].nuova = true; RE[id].reazione = true; RE[id].auto = false; Iris.EGGS[id] = RE[id]; }
  Iris.NUOVE.reazioni = Object.keys(RE);
  /* =============== RISVEGLIO (dopo il pisolino) ===============
     Quando stai fermo 12 minuti si appisola; al primo movimento del mouse si sveglia con una di queste, a caso.
     Ci va anche la Sveglia del primo lotto. */
  const WAKE = "quando si sveglia dal pisolino (dopo 12 minuti fermo, al primo movimento del mouse)";
  Iris.EGGS.sveglia.auto = false; Iris.EGGS.sveglia.risveglio = true; Iris.EGGS.sveglia.quando = WAKE;
  const closed = (T) => both(T, (e) => { e.lt = 0.86; e.op = 0.55; });
  const RS = {
    risv_spavento: { nome: "Salto dallo spavento", dur: 3000, desc: "Dorme, e di colpo salta su con gli occhi spalancati e tremanti, una gocciolina di sudore; poi si calma.",
      init(o, g) { g.l = [0, 1, 2, 3].map(() => mk(o.r.fx, "line", { stroke: "#fde047", "stroke-width": 0.9, "stroke-linecap": "round", opacity: 0 })); },
      t(o, T, k, s, a) { if (k < 0.12) return closed(T); const sc = 1 - seg(k, 0.6, 0.9); both(T, (e) => { e.w = 15 + 3 * sc; e.h = 21 + 5 * sc; e.rr = 6 + 3 * sc; e.dx = Math.sin(s * 50) * 0.6 * sc; }); T.body.y -= Math.sin(seg(k, 0.12, 0.25) * Math.PI) * 7; T.sweat = sc > 0.3 ? 1 : 0; },
      draw(o, t, k, s, a, g) { const q = seg(k, 0.12, 0.35); g.l.forEach((l, i) => { const an = (-150 + i * 40) * Math.PI / 180, r1 = 22 + q * 6; l.setAttribute("x1", f2(60 + Math.cos(an) * r1)); l.setAttribute("y1", f2(56 + Math.sin(an) * r1 * 0.5)); l.setAttribute("x2", f2(60 + Math.cos(an) * (r1 + 4))); l.setAttribute("y2", f2(56 + Math.sin(an) * (r1 + 4) * 0.5)); op(l, q > 0 && q < 1 ? 1 - q : 0); }); } },
    risv_stropiccia: { nome: "Si stropiccia gli occhi", dur: 3600, desc: "Si sveglia piano: sbatte le palpebre, strizza gli occhi come per stropicciarli, poi li apre bene.",
      t(o, T, k, s, a) { if (k < 0.15) return closed(T); if (k < 0.6) { const r = Math.sin(s * 14); both(T, (e) => { e.lt = 0.5 + r * 0.3; e.lb = 0.3; e.dx = r * 1.2; e.sc = 0.92; }); T.body.rot = Math.sin(s * 7) * 2; } else { const bl = Math.abs(Math.sin(seg(k, 0.6, 0.9) * Math.PI * 2)); both(T, (e) => { e.lt = bl * 0.7; }); } } },
    risv_sbadiglio: { nome: "Sbadiglio e stiracchiata", dur: 4200, desc: "Apre gli occhi con un grande sbadiglio, si allunga tutto verso l'alto e poi torna normale, contento.",
      init(o, g) { g.m = mk(o.r.fx, "ellipse", { cx: 60, cy: 75, rx: 2, ry: 0.5, fill: "currentColor", opacity: 0 }); },
      t(o, T, k, s, a) { if (k < 0.1) return closed(T); const y = Math.sin(seg(k, 0.1, 0.6) * Math.PI); both(T, (e) => { e.lt = 0.6 * y; e.h = 21 + y * 5; e.dy = -y * 2; }); T.body.sy = 1 + y * 0.06; T.body.sx = 1 - y * 0.03; if (k > 0.75) both(T, (e) => { e.lb = 0.5 * a; }); },
      draw(o, t, k, s, a, g) { const y = Math.sin(seg(k, 0.1, 0.6) * Math.PI); g.m.setAttribute("ry", f2(0.5 + y * 3)); g.m.setAttribute("rx", f2(2 + y)); op(g.m, y > 0.05 ? a : 0); } },
    risv_chi: { nome: "Chi è? Dove sono?", dur: 4000, desc: "Si sveglia confuso: guarda a destra e a sinistra, gli compare un punto di domanda, poi ti riconosce e sorride.",
      init(o, g) { g.q = txt(o.r.fx, "?", { x: 96, y: 52, "font-size": 10, fill: "currentColor", opacity: 0 }); },
      t(o, T, k, s, a) { if (k < 0.12) return closed(T); if (k < 0.7) { const side = Math.floor(seg(k, 0.12, 0.7) * 4) % 2 ? 1 : -1; both(T, (e) => { e.dx = side * 5; e.h = 22; }); T.L.h = 19; T.body.rot = side * 3; } else both(T, (e) => { e.lb = 0.55 * a; }); },
      draw(o, t, k, s, a, g) { tr(g.q, 0, Math.sin(s * 4) * 1, 1, Math.sin(s * 3) * 10); op(g.q, k > 0.3 && k < 0.7 ? 1 : 0); } },
    risv_bolla: { nome: "Bolla che scoppia", dur: 3500, desc: "La bolla del sonno gli si gonfia sotto il naso finché scoppia: si sveglia di soprassalto.",
      init(o, g) { g.b = mk(o.r.fx, "circle", { cx: 66, cy: 70, r: 1, fill: "rgba(186,230,253,.25)", stroke: "#bae6fd", "stroke-width": 0.8 }); g.sp = [0, 1, 2, 3, 4].map(() => mk(o.r.fx, "circle", { r: 0.7, fill: "#bae6fd", opacity: 0 })); },
      t(o, T, k, s, a) { if (k < 0.45) return closed(T); const sc = 1 - seg(k, 0.6, 0.9); both(T, (e) => { e.w = 15 + 3 * sc; e.h = 21 + 5 * sc; e.rr = 6 + 3 * sc; }); T.body.y -= Math.sin(seg(k, 0.45, 0.55) * Math.PI) * 5; },
      draw(o, t, k, s, a, g) { const r = k < 0.45 ? 1 + ease(k / 0.45) * 7 : 0; g.b.setAttribute("r", f2(r)); g.b.setAttribute("cx", f2(64 + r * 0.6)); op(g.b, r > 0 ? a : 0); const q = seg(k, 0.45, 0.65); g.sp.forEach((p, i) => { const an = (i / 5) * Math.PI * 2; p.setAttribute("cx", f2(68 + Math.cos(an) * q * 10)); p.setAttribute("cy", f2(68 + Math.sin(an) * q * 6)); op(p, q > 0 && q < 1 ? 1 - q : 0); }); } },
    risv_testa: { nome: "Testa che cade", dur: 3200, desc: "Sta crollando dal sonno, la testa va giù… e si tira su di scatto, occhi aperti come se niente fosse.",
      t(o, T, k, s, a) { if (k < 0.45) { closed(T); T.body.y += ease(k / 0.45) * 5; T.body.rot = -ease(k / 0.45) * 6; return; } const j = 1 - seg(k, 0.45, 0.6); T.body.y -= j * 3; both(T, (e) => { e.w = 16; e.h = 23; e.lt = 0; }); if (k > 0.7) both(T, (e) => { e.lt = 0.15; e.dx = Math.sin(s * 3) * 2; }); } },
  };
  for (const id in RS) { RS[id].nuova = true; RS[id].risveglio = true; RS[id].quando = WAKE; RS[id].auto = false; Iris.EGGS[id] = RS[id]; }
  Iris.NUOVE.risveglio = ["sveglia"].concat(Object.keys(RS));
  Iris.NUOVE.eggs = Iris.NUOVE.eggs.filter((id) => id !== "sveglia");

  /* =============== MANI: 20 ALTERNATIVE (concept) ===============
     Stesse manine tonde di "Ciao con la mano": niente braccia, solo due palline del colore degli occhi. */
  const H = (fn, init) => ({ init(o, g) { hands(o, g); if (init) init(o, g); }, draw: fn });
  const up = (k, a = 0.04, b = 0.16, c = 0.86, d = 0.97) => ease(seg(k, a, b)) * (1 - ease(seg(k, c, d)));
  const MA2 = {
    mano_ciao2: { nome: "Ciao con due mani", dur: 5000, desc: "Tutte e due le manine salutano ai lati degli occhi, contento.",
      t(o, T, k, s, a) { both(T, (e) => { e.lb = 0.55 * a; }); T.body.y -= Math.abs(Math.sin(s * 5)) * a; },
      ...H(function (o, t, k, s, a, g) { const u = up(k); putHand(g, 0, 26 + Math.sin(s * 10) * 3, 84 - u * 24, a); putHand(g, 1, 94 - Math.sin(s * 10) * 3, 84 - u * 24, a); }) },
    mano_cinque: { nome: "Batti cinque", dur: 4000, desc: "Una manina viene verso di te, sempre più grande, e \"pam!\": batti cinque con un lampo.",
      t(o, T, k, s, a) { both(T, (e) => { e.lb = (k > 0.55 ? 0.6 : 0.3) * a; e.dx = 2 * a; }); if (k > 0.5 && k < 0.6) T.body.x = -2; },
      ...H(function (o, t, k, s, a, g) { const q = ease(seg(k, 0.1, 0.5)), back = seg(k, 0.65, 0.95); putHand(g, 0, 90, 84 - q * 24 + back * 20, a, 1 + q * 1.8 - back); putHand(g, 1, 0, 0, 0); const f = k > 0.5 && k < 0.6 ? 1 : 0; g.fl.forEach((l, i) => { const an = i * Math.PI / 3; l.setAttribute("x1", f2(90 + Math.cos(an) * 10)); l.setAttribute("y1", f2(60 + Math.sin(an) * 10)); l.setAttribute("x2", f2(90 + Math.cos(an) * 14)); l.setAttribute("y2", f2(60 + Math.sin(an) * 14)); op(l, f); }); }, (o, g) => { g.fl = Array.from({ length: 6 }, () => mk(o.r.fx, "line", { stroke: "#fde047", "stroke-width": 1, "stroke-linecap": "round" })); }) },
    mano_fianchi: { nome: "Mani sui fianchi", dur: 4500, desc: "Mani ai lati in basso, si gonfia orgoglioso: \"fatto io!\".",
      t(o, T, k, s, a) { both(T, (e) => { e.lt = 0.25 * a; e.lb = 0.3 * a; e.dy = -2 * a; }); T.body.sx = 1 + 0.04 * a; T.body.rot = Math.sin(s * 2) * 1.5 * a; },
      ...H(function (o, t, k, s, a, g) { const u = up(k); putHand(g, 0, 30, 86 - u * 12, a); putHand(g, 1, 90, 86 - u * 12, a); }) },
    mano_gratta: { nome: "Si gratta la testa", dur: 4500, desc: "Una manina sopra la testa gratta in piccoli cerchi: non ha capito bene.",
      t(o, T, k, s, a) { T.L.lt = 0.05; T.R.lt = 0.32 * a; T.R.tilt = -14 * a; both(T, (e) => { e.dx = Math.sin(s * 0.9) * 2 * a; }); T.body.rot = 4 * a; },
      ...H(function (o, t, k, s, a, g) { const u = up(k); putHand(g, 0, 84 + Math.cos(s * 12) * 1.6, 30 + u * 17 + Math.sin(s * 12) * 1.2, a); putHand(g, 1, 0, 0, 0); }) },
    mano_mento: { nome: "Mano sul mento", dur: 5000, desc: "Una manina sotto, che tamburella piano: ci sta pensando, lo sguardo in alto.",
      t(o, T, k, s, a) { both(T, (e) => { e.dx = 3 * a; e.dy = -3.5 * a; e.h = 19; e.lb = 0.1; }); },
      ...H(function (o, t, k, s, a, g) { const u = up(k); putHand(g, 0, 70, 88 - u * 10 - Math.abs(Math.sin(s * 6)) * 1.2, a); putHand(g, 1, 0, 0, 0); }) },
    mano_sbadiglio: { nome: "Sbadiglio educato", dur: 4500, desc: "Sbadiglia mettendo la manina davanti alla bocca, poi sbatte le palpebre.",
      t(o, T, k, s, a) { const y = Math.sin(seg(k, 0.1, 0.7) * Math.PI); both(T, (e) => { e.lt = 0.6 * y; e.h = 21 + y * 4; e.dy = -y * 2; }); T.body.sy = 1 + y * 0.04; },
      ...H(function (o, t, k, s, a, g) { const y = Math.sin(seg(k, 0.1, 0.7) * Math.PI); putHand(g, 0, 61, 86 - y * 12, a * Math.min(1, y * 3)); putHand(g, 1, 0, 0, 0); }) },
    mano_stropiccia: { nome: "Si stropiccia gli occhi", dur: 4500, desc: "Con tutte e due le manine si stropiccia gli occhi in cerchio, poi li apre bene. Va bene anche per il risveglio.",
      t(o, T, k, s, a) { const r = k > 0.15 && k < 0.65; both(T, (e) => { e.lt = r ? 0.55 : 0; e.lb = r ? 0.3 : 0; }); if (k > 0.7) { const bl = Math.abs(Math.sin(seg(k, 0.7, 0.9) * Math.PI * 2)); both(T, (e) => { e.lt = bl * 0.6; }); } },
      ...H(function (o, t, k, s, a, g) { const u = up(k, 0.05, 0.15, 0.62, 0.72); putHand(g, 0, 46 + Math.cos(s * 12) * 2, 86 - u * 25 + Math.sin(s * 12) * 1.5, a, 1 + u * 0.4); putHand(g, 1, 74 - Math.cos(s * 12) * 2, 86 - u * 25 + Math.sin(s * 12 + 1) * 1.5, a, 1 + u * 0.4); }) },
    mano_tamburi: { nome: "Tamburello", dur: 5000, desc: "Le manine battono a turno sul bordo sotto, come su un tamburo, con le vibrazioni a ogni colpo.",
      t(o, T, k, s, a) { both(T, (e) => { e.lb = 0.35 * a; e.dy = -2 * a; }); T.body.y -= Math.abs(Math.sin(s * 9)) * 0.8 * a; },
      ...H(function (o, t, k, s, a, g) { const u = up(k); [0, 1].forEach((i) => { const hit = Math.max(0, Math.sin(s * 9 + i * Math.PI)); putHand(g, i, i ? 78 : 42, 90 - u * 12 - hit * 3, a); op(g.r[i], u * (hit < 0.2 ? 0.8 : 0)); g.r[i].setAttribute("cx", i ? 78 : 42); }); }, (o, g) => { g.r = [0, 1].map(() => mk(o.r.fx, "ellipse", { cy: 80, rx: 5, ry: 1, fill: "none", stroke: "currentColor", "stroke-width": 0.6 })); }) },
    mano_impaziente: { nome: "Tamburella impaziente", dur: 5000, desc: "Una manina tamburella veloce, occhi annoiati che guardano di lato: \"allora?\".",
      t(o, T, k, s, a) { both(T, (e) => { e.lt = 0.4 * a; e.dx = -3 * a; }); },
      ...H(function (o, t, k, s, a, g) { const u = up(k); putHand(g, 0, 92, 88 - u * 12 - Math.max(0, Math.sin(s * 22)) * 2, a); putHand(g, 1, 0, 0, 0); }) },
    mano_binocolo: { nome: "Binocolo", dur: 5500, desc: "Mette le manine intorno agli occhi come un binocolo e scruta l'orizzonte a destra e a sinistra.",
      t(o, T, k, s, a) { const x = Math.sin(s * 1.4) * 4; both(T, (e) => { e.dx = x * a; e.sc = 0.82; }); },
      ...H(function (o, t, k, s, a, g) { const u = up(k), x = Math.sin(s * 1.4) * 4; putHand(g, 0, 0, 0, 0); putHand(g, 1, 0, 0, 0); g.ring.forEach((r, i) => { r.setAttribute("cx", f2((i ? 74 : 46) + x)); r.setAttribute("cy", f2(61 + (1 - u) * 20)); op(r, u * a); }); }, (o, g) => { g.ring = [0, 1].map(() => mk(o.r.fx, "circle", { r: 10, fill: "none", stroke: "currentColor", "stroke-width": 3.4 })); }) },
    mano_facepalm: { nome: "Facepalm", dur: 4500, desc: "La manina si schiaffa sull'occhio destro e la testa scuote piano: \"ma dai…\".",
      t(o, T, k, s, a) { T.L.lt = 0.4 * a; T.L.tilt = -12 * a; if (k > 0.3) T.body.rot = Math.sin(s * 6) * 3 * a; },
      ...H(function (o, t, k, s, a, g) { const q = ease(seg(k, 0.1, 0.3)) * (1 - ease(seg(k, 0.85, 0.97))); putHand(g, 0, 74, 88 - q * 27, a, 1 + q * 1.6); putHand(g, 1, 0, 0, 0); }) },
    mano_palla: { nome: "Palleggia", dur: 5500, desc: "Fa rimbalzare una pallina con la manina, come a basket, e gli occhi vanno su e giù.",
      t(o, T, k, s, a) { const q = (s * 1.6) % 1; look(T, 92, 64 + Math.sin(q * Math.PI) * 10, a); },
      ...H(function (o, t, k, s, a, g) { const u = up(k), q = (s * 1.6) % 1, by = 66 + Math.sin(q * Math.PI) * 12; putHand(g, 0, 92, 84 - u * 24 - (q < 0.15 ? 1.5 : 0), a); putHand(g, 1, 0, 0, 0); g.b.setAttribute("cx", 92); g.b.setAttribute("cy", f2(by)); op(g.b, u * a); }, (o, g) => { g.b = mk(o.r.fx, "circle", { r: 2.6, fill: "#f97316" }); }) },
    mano_bacio: { nome: "Bacio volante", dur: 5000, desc: "Porta la manina alla bocca, la lancia verso di te e parte un cuoricino.",
      t(o, T, k, s, a) { both(T, (e) => { e.lb = 0.5 * a; }); if (k > 0.35 && k < 0.55) { T.L.lt = 0.6; } },
      ...H(function (o, t, k, s, a, g) { const q = ease(seg(k, 0.1, 0.35)), th = ease(seg(k, 0.4, 0.55)); putHand(g, 0, 60 + th * 30, 86 - q * 12 - th * 6 + seg(k, 0.85, 0.97) * 14, a); putHand(g, 1, 0, 0, 0); const hq = seg(k, 0.45, 0.95); tr(g.hrt, 70 + hq * 50, 70 - hq * 20, 1 + hq * 1.4); op(g.hrt, hq > 0 && hq < 1 ? a : 0); }, (o, g) => { g.hrt = mk(o.r.fx, "path", { d: HEART, fill: "#fb7185" }); }) },
    mano_evviva: { nome: "Mani in alto", dur: 4500, desc: "Alza tutte e due le manine e saltella: evviva!",
      t(o, T, k, s, a) { both(T, (e) => { e.lb = 0.6 * a; e.lt = 0.05; }); T.body.y -= Math.abs(Math.sin(s * 7)) * 3 * a; },
      ...H(function (o, t, k, s, a, g) { const u = up(k), j = Math.abs(Math.sin(s * 7)) * 3; putHand(g, 0, 32 - u * 4, 84 - u * 36 - j, a); putHand(g, 1, 88 + u * 4, 84 - u * 36 - j, a); }) },
    mano_shh: { nome: "Shh", dur: 4500, desc: "Una manina davanti alla bocca, occhi socchiusi: \"shh, silenzio\".",
      t(o, T, k, s, a) { both(T, (e) => { e.lt = 0.4 * a; e.lb = 0.2 * a; }); T.body.rot = -3 * a; },
      ...H(function (o, t, k, s, a, g) { const u = up(k); putHand(g, 0, 60, 88 - u * 13, a, 0.85); putHand(g, 1, 0, 0, 0); tr(g.t, 70, 74 - Math.sin(s * 3) * 1); op(g.t, u * a * (Math.sin(s * 3) > -0.3 ? 1 : 0.3)); }, (o, g) => { g.t = txt(o.r.fx, "shh", { "font-size": 5, fill: "currentColor" }); }) },
    mano_indica: { nome: "Indica qualcosa", dur: 5000, desc: "La manina scatta più volte verso destra, dove compare una stellina: \"guarda lì!\".",
      t(o, T, k, s, a) { both(T, (e) => { e.dx = 4 * a; e.lb = 0.25 * a; e.sc = 1.04; }); },
      ...H(function (o, t, k, s, a, g) { const u = up(k), p = Math.max(0, Math.sin(s * 6)); putHand(g, 0, 86 + p * 6, 84 - u * 20, a); putHand(g, 1, 0, 0, 0); tr(g.st, 118, 58, 0.8 + Math.abs(Math.sin(s * 3)) * 0.6, s * 60); op(g.st, u * a); }, (o, g) => { g.st = mk(o.r.fx, "path", { d: STAR, fill: "#fde68a" }); }) },
    mano_fronte: { nome: "Asciuga la fronte", dur: 4500, desc: "Passa la manina sopra gli occhi come per asciugarsi la fronte e vola via una goccia: \"fiuu\".",
      t(o, T, k, s, a) { both(T, (e) => { e.lb = (k > 0.6 ? 0.45 : 0.1) * a; e.lt = 0.2 * a; }); },
      ...H(function (o, t, k, s, a, g) { const q = seg(k, 0.2, 0.55); putHand(g, 0, 30 + q * 60, 46 + Math.sin(q * Math.PI) * -2 + (1 - up(k)) * 10, a * up(k)); putHand(g, 1, 0, 0, 0); const d = seg(k, 0.5, 0.8); tr(g.d, 92 + d * 12, 47 - Math.sin(d * Math.PI) * 6 + d * 10); op(g.d, d > 0 && d < 1 ? a : 0); }, (o, g) => { g.d = mk(o.r.fx, "path", { d: "M0 -3 Q2.2 0 0 2 Q-2.2 0 0 -3Z", fill: "#7dd3fc" }); }) },
    mano_megafono: { nome: "Chiama", dur: 4500, desc: "Mette le manine ai lati della bocca come un megafono e partono gli archi della voce.",
      t(o, T, k, s, a) { both(T, (e) => { e.w = 16; e.h = 22; e.dy = -2 * a; }); T.body.y -= Math.abs(Math.sin(s * 4)) * a; },
      ...H(function (o, t, k, s, a, g) { const u = up(k); putHand(g, 0, 53, 88 - u * 14, a, 0.8); putHand(g, 1, 67, 88 - u * 14, a, 0.8); g.w.forEach((w, i) => { const q = (s * 1.3 + i / 3) % 1; tr(w, 76 + q * 30, 74, 0.6 + q * 0.8); op(w, u * (1 - q)); }); }, (o, g) => { g.w = [0, 1, 2].map(() => mk(o.r.fx, "path", { d: "M0 -4 q3 4 0 8", fill: "none", stroke: "currentColor", "stroke-width": 1.2, "stroke-linecap": "round" })); }) },
    mano_cuore: { nome: "Cuore con le mani", dur: 5000, desc: "Le due manine si avvicinano sotto gli occhi e in mezzo si accende un cuore che pulsa.",
      t(o, T, k, s, a) { both(T, (e) => { e.lb = 0.5 * a; }); T.body.rot = Math.sin(s * 2) * 2 * a; },
      ...H(function (o, t, k, s, a, g) { const u = up(k), c = ease(seg(k, 0.2, 0.4)); putHand(g, 0, 60 - 22 + c * 13, 86 - u * 14, a); putHand(g, 1, 60 + 22 - c * 13, 86 - u * 14, a); tr(g.hrt, 60, 72, c * (2.4 + Math.sin(s * 8) * 0.25)); op(g.hrt, c * u * a); }, (o, g) => { g.hrt = mk(o.r.fx, "path", { d: HEART, fill: "#fb7185" }); }) },
  };
  for (const id in MA2) { MA2[id].nuova = true; MA2[id].concept = true; MA2[id].auto = false; Iris.EGGS[id] = MA2[id]; }
  Iris.NUOVE.mani = Iris.NUOVE.mani.concat(Object.keys(MA2));
})();
